import { GRID_INDENT, STAGE_WIDTH } from "./GeomStage";

export const FIGURE_AREA = 4;

export const FIGURE1 = {
  COLOR: '#83E8FF',
  POINTS: [
    1 * GRID_INDENT, 11 * GRID_INDENT,
    1 * GRID_INDENT, 13 * GRID_INDENT,
    4 * GRID_INDENT, 13 * GRID_INDENT,
    4 * GRID_INDENT, 12 * GRID_INDENT,
    2 * GRID_INDENT, 12 * GRID_INDENT,
    2 * GRID_INDENT, 11 * GRID_INDENT
  ]
};

export const FIGURE2 = {
  COLOR: '#FFA9E7',
  POINTS: [
    STAGE_WIDTH - 4 * GRID_INDENT, 1 * GRID_INDENT,
    STAGE_WIDTH - 4 * GRID_INDENT, 2 * GRID_INDENT,
    STAGE_WIDTH - 2 * GRID_INDENT, 2 * GRID_INDENT,
    STAGE_WIDTH - 2 * GRID_INDENT, 3 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 3 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 1 * GRID_INDENT
  ]
};

export const FIGURE3 = {
  COLOR: '#CCED00',
  POINTS: [
    STAGE_WIDTH - 4 * GRID_INDENT, 12 * GRID_INDENT,
    STAGE_WIDTH - 4 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 11 * GRID_INDENT,
    STAGE_WIDTH - 2 * GRID_INDENT, 11 * GRID_INDENT,
    STAGE_WIDTH - 2 * GRID_INDENT, 12 * GRID_INDENT
  ]
};

export const FIGURE4 = {
  COLOR: '#FFEF5B',
  POINTS: [
    1 * GRID_INDENT, 1 * GRID_INDENT,
    1 * GRID_INDENT, 3 * GRID_INDENT,
    2 * GRID_INDENT, 3 * GRID_INDENT,
    2 * GRID_INDENT, 2 * GRID_INDENT,
    4 * GRID_INDENT, 2 * GRID_INDENT,
    4 * GRID_INDENT, 1 * GRID_INDENT
  ]
};

export const FIGURE5 = {
  COLOR: '#CCED00',
  POINTS: [
    STAGE_WIDTH - 5 * GRID_INDENT, 11 * GRID_INDENT,
    STAGE_WIDTH - 5 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 11 * GRID_INDENT
  ],
};
